create component Logo
WildCodeSchool/2022-03-JS-Lille-project-2-g1-superheroes pull request #14
Opened 2022-04-20 09:06 UTC by jeremyjorand

2022-04-20 09:10 UTC, mastemm approved these changes

2022-04-21 09:38 UTC, mastemm submitted a review, later dismissed

2022-04-21 10:46 UTC, LuigiMenez commented on frontend/src/App.jsx
Warning the blank line

2022-04-21 10:46 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-04-21 12:25 UTC, mastemm submitted a review, later dismissed
no more blank space

2022-04-21 13:07 UTC, mastemm submitted a review, later dismissed

2022-04-21 13:14 UTC, LuigiMenez approved these changes, later dismissed
Ok for me

2022-04-21 13:55 UTC, LoicBrassart approved these changes, later dismissed
Saw no Evil

2022-04-21 14:38 UTC, mastemm approved these changes

2022-04-22 05:24 UTC, LoicBrassart commented
- Fix your conflicts
- Use the "reviewers" *and* the "assignees" fields (otherwise I can't se it)
- Don't assign me at all (Luigi'll do it)

2022-04-27 07:10 UTC, mastemm approved these changes, later dismissed

2022-04-27 08:32 UTC, LuigiMenez approved these changes, later dismissed
Ok for me

2022-04-27 12:44 UTC, LoicBrassart requested changes
Fix this plz (and test)

2022-04-27 12:44 UTC, LoicBrassart commented on frontend/src/App.jsx
> +    <div className="App">
Nope, that'd break your whole App ! :scream:

2022-04-27 13:00 UTC, Hamza-Luciano approved these changes, later dismissed
modify app.jsx

2022-04-27 14:14 UTC, LuigiMenez commented on frontend/src/App.jsx
> +
Blank line

2022-04-27 14:15 UTC, LuigiMenez commented on frontend/src/App.jsx
> +             </Routes>
Warning indentation

2022-04-27 14:15 UTC, LuigiMenez requested changes
Verify a prettier for automatic indentation

2022-04-27 14:24 UTC, Hamza-Luciano approved these changes
ok for us :'(

2022-04-27 14:39 UTC, LuigiMenez approved these changes
Ok for me.

2022-04-28 10:22 UTC, LoicBrassart approved these changes
Saw no Evil

2022-04-28 10:27 UTC, merged