Jarvis
WildCodeSchool/2022-03-JS-Lille-project-2-g1-superheroes pull request #23
Opened 2022-04-27 07:33 UTC by RomainLF

2022-04-27 08:19 UTC, Hamza-Luciano submitted a review, later dismissed
ok for me

2022-04-27 08:39 UTC, LuigiMenez submitted a review, later dismissed
Ok for me

2022-04-27 12:50 UTC, LoicBrassart requested changes
Some Evils to fix

2022-04-27 12:50 UTC, LoicBrassart commented on frontend/src/components/Jarvis/Modal/index.jsx
> +      <>
You can remove the Fragment, it does nothing in this case

2022-04-27 12:50 UTC, LoicBrassart commented on frontend/src/components/Jarvis/Modal/index.jsx
> +          <div className="app">{}</div>
Why `{}` ?
`<div className="app" />` does the same job

2022-04-27 12:50 UTC, LoicBrassart commented on frontend/src/components/Jarvis/Modal/style.jsx
> +    z-index: 1000;
Meh... That's not top-quality code right here -_-

2022-04-27 12:50 UTC, LoicBrassart commented on frontend/src/components/Jarvis/Modal/style.jsx
> +    z-index: 1000;
Same goes here

2022-04-27 12:50 UTC, LoicBrassart commented on frontend/src/components/Jarvis/index.jsx
> +      // insert your filter here <3
Maybe you could remove my silly comments from your code ? :rofl:

2022-04-27 13:08 UTC, Hamza-Luciano approved these changes, later dismissed
ok for us

2022-04-27 14:00 UTC, LuigiMenez commented on frontend/src/components/Jarvis/Modal/index.jsx
> +              Close card
a little problem indentation

2022-04-27 14:00 UTC, LuigiMenez requested changes
A little problem indentation

2022-04-27 14:04 UTC, Hamza-Luciano approved these changes, later dismissed
ok for us

2022-04-27 14:21 UTC, LuigiMenez requested changes
bad indentation

2022-04-27 14:27 UTC, Hamza-Luciano approved these changes
ok for us

2022-04-27 14:42 UTC, LuigiMenez approved these changes
Ok for me.

2022-04-28 10:24 UTC, LoicBrassart approved these changes
No more Evil

2022-04-28 10:27 UTC, merged