Filtre
WildCodeSchool/2022-03-JS-Lille-project-2-g1-superheroes pull request #42
Opened 2022-05-05 14:30 UTC by jeremyjorand

2022-05-05 14:31 UTC, RomainLF submitted a review, later dismissed

2022-05-05 23:02 UTC, LuigiMenez commented on frontend/src/components/Filtre/index.jsx
> +  // console.log(valueStrengh);
No dead code

2022-05-05 23:02 UTC, LuigiMenez commented on frontend/src/components/Filtre/index.jsx
> +    // console.log(heroes.map((hero) => hero?.appearance?.race));
No dead code

2022-05-05 23:05 UTC, LuigiMenez requested changes
No Dead code

2022-05-06 06:41 UTC, RomainLF submitted a review, later dismissed

2022-05-06 12:05 UTC, LuigiMenez commented on frontend/src/components/Univers/index.jsx
> +              }
We can make it shorter: if (choiceRace === "false" || choiceRace === false)

2022-05-06 12:05 UTC, LuigiMenez requested changes
We can make it shorter: if (choiceRace === "false" || choiceRace === false)

2022-05-06 12:52 UTC, RomainLF approved these changes, later dismissed

2022-05-06 12:55 UTC, LuigiMenez approved these changes, later dismissed
Ok for me.

2022-05-09 09:49 UTC, LuigiMenez commented on frontend/src/components/Jarvis/Modal/index.jsx
> +      {/* eslint-disable-next-line */}
nope

2022-05-09 09:50 UTC, LuigiMenez requested changes
No, there are ways to close a modal without disabling eslint

2022-05-10 08:20 UTC, RomainLF approved these changes, later dismissed

2022-05-10 11:27 UTC, LuigiMenez commented on frontend/src/components/Jarvis/Modal/index.jsx
> +      {/* eslint-disable-next-line */}
eslint is not deactivated

2022-05-10 11:28 UTC, LuigiMenez requested changes
Not deactivated ESlint

2022-05-10 11:59 UTC, ThomasDCW approved these changes

2022-05-10 12:00 UTC, ThomasDCW approved these changes, later dismissed

2022-05-10 14:26 UTC, LuigiMenez approved these changes
Ok for me.

2022-05-10 14:27 UTC, ThomasDCW submitted a review, later dismissed

2022-05-10 14:28 UTC, RomainLF approved these changes, later dismissed

2022-05-10 14:28 UTC, LuigiMenez requested changes
Fix Conflict

2022-05-11 07:19 UTC, ThomasDCW approved these changes

2022-05-11 07:36 UTC, LuigiMenez approved these changes
Ok for me.

2022-05-11 08:05 UTC, LoicBrassart approved these changes
Fine by me, but there are a lot of "little" errors and typos you could have skipped

2022-05-11 08:05 UTC, LoicBrassart commented on frontend/src/components/Filtre/style.jsx
> +  }
...

2022-05-11 08:05 UTC, LoicBrassart commented on frontend/src/components/Card/index.jsx
> +
Useless empty line

2022-05-11 08:05 UTC, LoicBrassart commented on frontend/src/components/Filtre/index.jsx
> +            {" "}
Useless space ?

2022-05-11 08:05 UTC, LoicBrassart commented on frontend/src/components/Filtre/index.jsx
> +            })}{" "}
Same

2022-05-11 08:08 UTC, merged